project:
  type: website
  resources:
    - glossary/terms.yml
    - assets/js/*.js

website:
  title: "Team of Biostatistics"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: team.qmd
        text: Our Team

      - href: software.qmd
        text: Statistical Software

      - href: research.qmd
        text: Interesting Research

      - href: books.qmd
        text: Biostatistics Books

      - href: cheatsheet.qmd
        text: Cheat sheet

      - href: methods.qmd
        text: Data Analysis Methods

      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    include-in-header: assets/views-include.html